import React from "react";

export const DinoIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 40 40" width="40" height="40" xmlns="http://www.w3.org/2000/svg" {...props}>
  <rect x="16" y="0" width="2" height="2" fill="currentColor" />
  <rect x="18" y="0" width="2" height="2" fill="currentColor" />
  <rect x="20" y="0" width="2" height="2" fill="currentColor" />
  <rect x="22" y="0" width="2" height="2" fill="currentColor" />
  <rect x="24" y="0" width="2" height="2" fill="currentColor" />
  <rect x="26" y="0" width="2" height="2" fill="currentColor" />
  <rect x="28" y="0" width="2" height="2" fill="currentColor" />
  <rect x="30" y="0" width="2" height="2" fill="currentColor" />
  <rect x="14" y="2" width="2" height="2" fill="currentColor" />
  <rect x="16" y="2" width="2" height="2" fill="currentColor" />
  <rect x="18" y="2" width="2" height="2" fill="currentColor" />
  <rect x="20" y="2" width="2" height="2" fill="currentColor" />
  <rect x="22" y="2" width="2" height="2" fill="currentColor" />
  <rect x="24" y="2" width="2" height="2" fill="currentColor" />
  <rect x="26" y="2" width="2" height="2" fill="currentColor" />
  <rect x="28" y="2" width="2" height="2" fill="currentColor" />
  <rect x="30" y="2" width="2" height="2" fill="currentColor" />
  <rect x="14" y="4" width="2" height="2" fill="currentColor" />
  <rect x="16" y="4" width="2" height="2" fill="currentColor" />
  <rect x="20" y="4" width="2" height="2" fill="currentColor" />
  <rect x="22" y="4" width="2" height="2" fill="currentColor" />
  <rect x="24" y="4" width="2" height="2" fill="currentColor" />
  <rect x="26" y="4" width="2" height="2" fill="currentColor" />
  <rect x="28" y="4" width="2" height="2" fill="currentColor" />
  <rect x="14" y="6" width="2" height="2" fill="currentColor" />
  <rect x="16" y="6" width="2" height="2" fill="currentColor" />
  <rect x="18" y="6" width="2" height="2" fill="currentColor" />
  <rect x="20" y="6" width="2" height="2" fill="currentColor" />
  <rect x="22" y="6" width="2" height="2" fill="currentColor" />
  <rect x="24" y="6" width="2" height="2" fill="currentColor" />
  <rect x="26" y="6" width="2" height="2" fill="currentColor" />
  <rect x="28" y="6" width="2" height="2" fill="currentColor" />
  <rect x="14" y="8" width="2" height="2" fill="currentColor" />
  <rect x="16" y="8" width="2" height="2" fill="currentColor" />
  <rect x="18" y="8" width="2" height="2" fill="currentColor" />
  <rect x="20" y="8" width="2" height="2" fill="currentColor" />
  <rect x="22" y="8" width="2" height="2" fill="currentColor" />
  <rect x="24" y="8" width="2" height="2" fill="currentColor" />
  <rect x="26" y="8" width="2" height="2" fill="currentColor" />
  <rect x="28" y="8" width="2" height="2" fill="currentColor" />
  <rect x="14" y="10" width="2" height="2" fill="currentColor" />
  <rect x="16" y="10" width="2" height="2" fill="currentColor" />
  <rect x="18" y="10" width="2" height="2" fill="currentColor" />
  <rect x="20" y="10" width="2" height="2" fill="currentColor" />
  <rect x="22" y="10" width="2" height="2" fill="currentColor" />
  <rect x="14" y="12" width="2" height="2" fill="currentColor" />
  <rect x="16" y="12" width="2" height="2" fill="currentColor" />
  <rect x="18" y="12" width="2" height="2" fill="currentColor" />
  <rect x="20" y="12" width="2" height="2" fill="currentColor" />
  <rect x="22" y="12" width="2" height="2" fill="currentColor" />
  <rect x="24" y="12" width="2" height="2" fill="currentColor" />
  <rect x="26" y="12" width="2" height="2" fill="currentColor" />
  <rect x="14" y="14" width="2" height="2" fill="currentColor" />
  <rect x="16" y="14" width="2" height="2" fill="currentColor" />
  <rect x="18" y="14" width="2" height="2" fill="currentColor" />
  <rect x="20" y="14" width="2" height="2" fill="currentColor" />
  <rect x="22" y="14" width="2" height="2" fill="currentColor" />
  <rect x="0" y="16" width="2" height="2" fill="currentColor" />
  <rect x="14" y="16" width="2" height="2" fill="currentColor" />
  <rect x="16" y="16" width="2" height="2" fill="currentColor" />
  <rect x="18" y="16" width="2" height="2" fill="currentColor" />
  <rect x="20" y="16" width="2" height="2" fill="currentColor" />
  <rect x="0" y="18" width="2" height="2" fill="currentColor" />
  <rect x="2" y="18" width="2" height="2" fill="currentColor" />
  <rect x="12" y="18" width="2" height="2" fill="currentColor" />
  <rect x="14" y="18" width="2" height="2" fill="currentColor" />
  <rect x="16" y="18" width="2" height="2" fill="currentColor" />
  <rect x="18" y="18" width="2" height="2" fill="currentColor" />
  <rect x="20" y="18" width="2" height="2" fill="currentColor" />
  <rect x="22" y="18" width="2" height="2" fill="currentColor" />
  <rect x="0" y="20" width="2" height="2" fill="currentColor" />
  <rect x="2" y="20" width="2" height="2" fill="currentColor" />
  <rect x="4" y="20" width="2" height="2" fill="currentColor" />
  <rect x="12" y="20" width="2" height="2" fill="currentColor" />
  <rect x="14" y="20" width="2" height="2" fill="currentColor" />
  <rect x="16" y="20" width="2" height="2" fill="currentColor" />
  <rect x="18" y="20" width="2" height="2" fill="currentColor" />
  <rect x="20" y="20" width="2" height="2" fill="currentColor" />
  <rect x="22" y="20" width="2" height="2" fill="currentColor" />
  <rect x="0" y="22" width="2" height="2" fill="currentColor" />
  <rect x="2" y="22" width="2" height="2" fill="currentColor" />
  <rect x="4" y="22" width="2" height="2" fill="currentColor" />
  <rect x="6" y="22" width="2" height="2" fill="currentColor" />
  <rect x="8" y="22" width="2" height="2" fill="currentColor" />
  <rect x="10" y="22" width="2" height="2" fill="currentColor" />
  <rect x="12" y="22" width="2" height="2" fill="currentColor" />
  <rect x="14" y="22" width="2" height="2" fill="currentColor" />
  <rect x="16" y="22" width="2" height="2" fill="currentColor" />
  <rect x="18" y="22" width="2" height="2" fill="currentColor" />
  <rect x="20" y="22" width="2" height="2" fill="currentColor" />
  <rect x="22" y="22" width="2" height="2" fill="currentColor" />
  <rect x="2" y="24" width="2" height="2" fill="currentColor" />
  <rect x="4" y="24" width="2" height="2" fill="currentColor" />
  <rect x="6" y="24" width="2" height="2" fill="currentColor" />
  <rect x="8" y="24" width="2" height="2" fill="currentColor" />
  <rect x="10" y="24" width="2" height="2" fill="currentColor" />
  <rect x="12" y="24" width="2" height="2" fill="currentColor" />
  <rect x="14" y="24" width="2" height="2" fill="currentColor" />
  <rect x="16" y="24" width="2" height="2" fill="currentColor" />
  <rect x="18" y="24" width="2" height="2" fill="currentColor" />
  <rect x="20" y="24" width="2" height="2" fill="currentColor" />
  <rect x="22" y="24" width="2" height="2" fill="currentColor" />
  <rect x="4" y="26" width="2" height="2" fill="currentColor" />
  <rect x="6" y="26" width="2" height="2" fill="currentColor" />
  <rect x="8" y="26" width="2" height="2" fill="currentColor" />
  <rect x="10" y="26" width="2" height="2" fill="currentColor" />
  <rect x="12" y="26" width="2" height="2" fill="currentColor" />
  <rect x="14" y="26" width="2" height="2" fill="currentColor" />
  <rect x="16" y="26" width="2" height="2" fill="currentColor" />
  <rect x="18" y="26" width="2" height="2" fill="currentColor" />
  <rect x="20" y="26" width="2" height="2" fill="currentColor" />
  <rect x="22" y="26" width="2" height="2" fill="currentColor" />
  <rect x="6" y="28" width="2" height="2" fill="currentColor" />
  <rect x="8" y="28" width="2" height="2" fill="currentColor" />
  <rect x="10" y="28" width="2" height="2" fill="currentColor" />
  <rect x="12" y="28" width="2" height="2" fill="currentColor" />
  <rect x="14" y="28" width="2" height="2" fill="currentColor" />
  <rect x="16" y="28" width="2" height="2" fill="currentColor" />
  <rect x="18" y="28" width="2" height="2" fill="currentColor" />
  <rect x="20" y="28" width="2" height="2" fill="currentColor" />
  <rect x="22" y="28" width="2" height="2" fill="currentColor" />
  <rect x="8" y="30" width="2" height="2" fill="currentColor" />
  <rect x="10" y="30" width="2" height="2" fill="currentColor" />
  <rect x="12" y="30" width="2" height="2" fill="currentColor" />
  <rect x="14" y="30" width="2" height="2" fill="currentColor" />
  <rect x="16" y="30" width="2" height="2" fill="currentColor" />
  <rect x="18" y="30" width="2" height="2" fill="currentColor" />
  <rect x="20" y="30" width="2" height="2" fill="currentColor" />
  <rect x="10" y="32" width="2" height="2" fill="currentColor" />
  <rect x="12" y="32" width="2" height="2" fill="currentColor" />
  <rect x="14" y="32" width="2" height="2" fill="currentColor" />
  <rect x="16" y="32" width="2" height="2" fill="currentColor" />
  <rect x="18" y="32" width="2" height="2" fill="currentColor" />
  <rect x="10" y="34" width="2" height="2" fill="currentColor" />
  <rect x="12" y="34" width="2" height="2" fill="currentColor" />
  <rect x="16" y="34" width="2" height="2" fill="currentColor" />
  <rect x="18" y="34" width="2" height="2" fill="currentColor" />
  <rect x="10" y="36" width="2" height="2" fill="currentColor" />
  <rect x="12" y="36" width="2" height="2" fill="currentColor" />
  <rect x="20" y="36" width="2" height="2" fill="currentColor" />
  <rect x="10" y="38" width="2" height="2" fill="currentColor" />
  </svg>
);
